language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew war

after_success:
  - mkdir codedeploy
  - zip -r csye6225-fall2017.zip build/libs/ROOT.war appspec.yml
  - ls -al
  - mv csye6225-fall2017.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

deploy:
<<<<<<< HEAD
  -provider: s3
  access_key_id: AKIAI7WX5ZOW4AS6OV5A
  secure_access_key:
    secure: "FgYqfw0SFWPPX5nl4KY9aaiVSK2ZP2cBplzuqj+4iLXSVfkJs5reKA/nQ1A6C6n8dH9zkyX6kTizYINO0vDQHePDwgaKRbH959MXsxM5dMAeYm6CSkUOeGMmKfjEQt29HRTq35LNpbeDec2cxslC+W2Yfxzn8Lvtw/G8ooOChjJ3Vlly2tka3mZX0NXhStFdf7xo6zx4QZVmuVK7x8Y9Y//GhMEhmHdtXyIguULwKdo1hNUQhMi4k1S5GSjILsazJ9VGwi63IBuLGebr8+dd1Z3vNxyuGTHufEQg2od9PmMzzrKwE6FXIt0DyWxo4EYTFilIFzratj7lY5+KvuZ3cVFqVXRD/EnGext12IAUvKAFkcMvpNBlXvJywke+SVGPGEnT3TeOeNs3XCxczjWkHXMVajtqGNqqj8vlCLSzoxdM+Zr39qONnNJbGt5DGnMlhJI/46WDlgql3KD77fN+ZauA3gUX2ExnfQGEjz9II06y7DXb4twSscCNfwb45Rl71hLkv6YrwG2pjlF/DWO7z+RBe/Mpsl7iyGQ3UPiCwiBRIMXhcYA27bcaYJyZpKEyzMUE1kxM/e1XSkql8yScxMC//s/eWEuOhDCs702NhhxVDrjahOKHVgUrk3x8Z9GlKFHjulzeWcn0GGXoozm61EE+IlIpdn7dFrydtd7oCZ0="
  local_dir: codedeploy
  bucket: code-deploy.csye6225-fall2017-patilman.me
  region: us-east-1
  skip_cleanup: true
=======
  - provider: s3
  - access_key_id:
  - secret_access_key:
   secure: 3finP0xvgs4vlgbEhsMBnfaGLFoOUbRSi6+PJ0pb49PauNeb0/HTs7f0C+TuMeYJNLPJ5KsXnRdKQhGwtqrGIuu0xtVd218Ra0i6fF1V7xOFbrFDXJPfssRgYUBw/ZGVTZtLONs4QXlDoF8o8aJi/+kVYng76nWch44d3yc7MStpHJ4tc8TedbxI8nuAubXII4JyPHIZGJEfimRxnAfzE4rZRg5RRdLbx6Qzrs4ouuFqCaG6NnfGYKxLWqOaQatA2X7QEdGSyiZa/OsZe5qI4DeSn8R3aswT4zsucFmMODwPjLGTDWHmuGnzddMhxb8C2oGhc+xj8WKKAZ0T0XCOvAhw2hmSh2XJ7IGMx0N7D7bHiUWaZC/hPo2XYio1hBo7iCFrzqLzBHQs9hGy7prtKSsf9gboK4vchuvAOISWITzbvT61LQfuQELjg3X8n4VohosZZ7EF1GV+PGVepIVRlewoMliR6OULbw82fJAtBOVBf4A6X/zgHBMdPVyMlQAqaPrMupzFWA/VWMlpDeBLUULPzXTvn1Jbq5pnCQxA3GAUrsokVlsDn9I/t3cSb1PwVeBSrztGOEtGcbePDct+Io+738e34xKrd7q1HDJcnSTgIe5VlKpF/UIvXKAkwK8Z/5P4cZpSWCw8n40jGfzZJoKet1XsEB2T7JSStW8QKkA=
   local_dir: codedeploy
   bucket: code-deploy.csye6225.com
   region: us-east-1
   skip_cleanup: true

>>>>>>> 5e853b2503004c3de1ed47eef72988648bf735f5


notifications:
  username:
    recipients:
      - patil.man@husky.neu.edu
