language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew war

after_success:
  - mkdir codedeploy
  - zip -r csye6225-fall2017.zip build/libs/ROOT.war appspec.yml
  - ls -al
  - mv csye6225-fall2017.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

deploy:
  - provider: s3


notifications:
  username:
    recipients:
      - patil.man@husky.neu.edu
