language: java
jdk:
- oraclejdk8
sudo: false
install: true
script:
- "./gradlew build"
after_success:
- pwd
- cd build/libs/
- ls -al
- cd ../..
- pwd
- mkdir codedeploy
- zip -r csye6225-fall2017.zip build/libs/ROOT.war appspec.yml restartTomcat8.sh
- ls -al
- mv csye6225-fall2017.zip codedeploy/
- ls -al
- pwd
- cd codedeploy
- ls -al
- pwd
before_deploy:
- mkdir -p dpl_cd_upload
- mv csye-6225-fall2017.zip dpl_cd_upload/csye6225-fall2017.zip
- pwd
- ls -al
deploy:
- provider: s3
  access_key_id: AKIAJQQ7YTHQAKXFFVDQ
  secret_access_key: &1
    secure: jHaSu81Yih6uW4imu3iaDJLCl6PnhPJGeRqIL9Zuyn3E0jkie5SJtn/mHT5MlQZZ5n+pYYoIQm+OzBCvA5V8eYEHEZejxKiFgthsjm9ChpTnOgdeGfBUilRVlm/gtxDxwusShaXTUZX19zusXEYXR1QPS6Bt/tfBEKig+ETN2hAmehHpOVGWGcahf2xhuDpKis2fjoVVO9g8x4+N51s7x2SpG6QJ607G0AcRBu0gwWPvROt+RihZCzKqdPAZw8WBlyb0izCV3cDvoXbJfijL4rWNCzg5HoFufSrzp9KQ4/cb4ExVpS8pnXGQxCqtm0N/A0JNFhX5mvo2G7Wwt6xUk/m90u7b3+QshZwFS0ybXlRm+WkrxNwm3MgiNtVLcd1lK9Y+vUN6yhJFxeLtDSVDBPITZLUHACTqVfxl6b07qLYGa2GbOJNWai2kI0Xv4bhBkpua0LRZS9uSCciam9O53ILD9jkKnu7YmIlB39beTGPLQUCgXPiav95j71riS/MwVGEllOR8c9j0fSNSQgqQWiWFTSaasjlpNjaj+34ppdA63LwEZzltLmjD+rBYLWQJIAuZzobGVf8sDeOH9WmgCzHCxu+WCMJyjQwoZGlcA0HlogfHzDEzQsIeRHAgZUldsUtAM0hz2EssIrvr96yh5MWe5pJ67q/hhI2z+25OLeo=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: patilm5191/csye6225-fall2017
    branch: assignment7
  bucket: "$bucket_name"
- provider: codedeploy
  access_key_id: AKIAJQQ7YTHQAKXFFVDQ
  secret_access_key: *1
  bucket: "$bucket_name"
  key: csye6225-fall2017.zip
  bundle_type: zip
  application: csye6225-fall2017
  deployment_group: csye6225-fall2017-group
  on: *2
notifications:
  username:
    recipients:
    - patil.man@husky.neu.edu
